targets:
  $default:
    sources:
      - lib/**
      - swagger_config/**
      - $package$
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "swagger_config/"
          output_folder: "lib/api/"
          input_urls:
            - url: "https://d09d-78-175-53-255.ngrok-free.app/swagger/v1/swagger.json"